# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - moodle_net

  moodle:
    image: docker.io/bitnami/moodle:5.0
    ports:
      - '8082:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - PHP_UPLOAD_MAX_FILESIZE=600M
      - PHP_POST_MAX_SIZE=600M
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodle_moodledata:/bitnami/moodledata'
      - './uploads.ini:/usr/local/etc/php/conf.d/uploads.ini'
    depends_on:
      - mariadb
    networks:
      - moodle_net

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodle_moodledata:
    driver: local

networks:
  moodle_net:
    driver: bridge